#!/bin/bash

# Wrapper script to flip screen (and touchpad) on GLIMMER (Lenovo 11e Chromebook) devices

# Safety
set -o errexit -o nounset -o pipefail

# Names
OUT="eDP-1"
TPAD="Elan Touchpad"
TSCR="Atmel maXTouch Touchscreen"

# Current rotation
ROT="$(xrandr --query --verbose | awk "/$OUT/ { print \$6 }")"

# Switch depending on current rotation
case "$ROT" in 
    "normal")
    xrandr --orientation inverted
    xinput set-prop "$TPAD" "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1 || true
    xinput set-prop "$TSCR" "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1 || true
    ;;
    "inverted")
    xrandr --orientation normal
    xinput set-prop "$TPAD" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1 || true
    xinput set-prop "$TSCR" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1 || true
    ;;
esac
