#!/bin/bash
DIR="$HOME/.config/transmission-daemon/torrents"
FILES=$(ls -t $DIR)
IFS=$'\n'
for FILE in $FILES; do
  AGE=$(($(date +%s) - $(stat -c %Y $DIR/$FILE)))
  AGE=$(($AGE / 86400))
  echo $(printf "%02dd" "$AGE") $FILE
done
