#!/bin/bash

### List transmission torrents sorted by AGE

# Bash safety
set -o errexit -o nounset -o pipefail

# Torrents directory
DIR="$HOME/.config/transmission-daemon/torrents"

# Get list of torrents
TORRENTS=$(ls -t "$DIR")

# Print torrents
IFS=$'\n'
for TORRENT in $TORRENTS; do
    printf -v EPOCH "%(%s)T"
    AGE=$(stat -c %Y "$DIR/$TORRENT")
    DAYS=$((($EPOCH-$AGE)/86400))
    printf "%02dd %s\n" "$DAYS" "$TORRENT"
done
