#!/bin/bash

# error handling
set -o errexit -o nounset -o pipefail

# setup environment
PATH="/snap/bin:$PATH"
cd "$1"

# set output name format
OUTPUT_FMT="%(title)s_%(id)s.%(ext)s"
if [ -e ".output_fmt" ]; then
    OUTPUT_FMT="$(<.output_fmt)"
    echo "$1: custom name format: $OUTPUT_FMT"
fi

# download playlist
yt-dlp \
    --add-metadata \
    --audio-format aac \
    --audio-quality 0 \
    --batch-file ".playlist_url" \
    --continue \
    --download-archive ".download_ids" \
    --embed-thumbnail \
    --extract-audio \
    --metadata-from-title "%(title)s" \
    --output "$OUTPUT_FMT" \
    --parse-metadata "title:%(title)s" \
    --parse-metadata "uploader:%(artist)s" \
    --paths "." \
    --restrict-filenames

# read playlist IDs and create lookup array
mapfile -t IDS < <(yt-dlp --batch-file ".playlist_url" --flat-playlist --print 'id')
declare -A LOOKUP
for ID in "${IDS[@]}"; do
    LOOKUP["$ID"]=1
done

# remove files with IDs that do not exist in playlist
for FILE in *; do
    # ID pattern: 11 chars, A–Z, a–z, 0–9, -, _
    if [[ $FILE =~ ([A-Za-z0-9_-]{11})\.[^.]+$ ]]; then
       FILE_ID="${BASH_REMATCH[1]}"
       if [[ ! ${LOOKUP["$FILE_ID"]+_} ]]; then
           echo "$FILE: $FILE_ID: NOT found in playlist IDs!"
           rm --verbose "$FILE"
       fi
    else
       echo "$FILE: skipping: no track ID!"
    fi
done
