#!/bin/bash

# error handling
set -o errexit -o nounset -o pipefail

# setup environment
PATH="$HOME/bin:$PATH"
cd "$1"

# set output name format
OUTPUT_FMT="%(title)s_%(id)s.%(ext)s"
if [ -e ".output_fmt" ]; then
    OUTPUT_FMT="$(<.output_fmt)"
    echo "$1: custom name format: $OUTPUT_FMT"
fi

# download playlist
yt-dlp \
    --add-metadata \
    --audio-format aac \
    --audio-quality 0 \
    --batch-file ".playlist_url" \
    --continue \
    --convert-thumbnails jpg \
    --download-archive ".download_ids" \
    --embed-thumbnail \
    --extract-audio \
    --js-runtimes node:/usr/bin/nodejs \
    --metadata-from-title "%(title)s" \
    --output "$OUTPUT_FMT" \
    --parse-metadata "title:%(title)s" \
    --parse-metadata "uploader:%(artist)s" \
    --paths "." \
    --restrict-filenames
